"""empty message

Revision ID: 1e75b522a118
Revises: ae346256b650
Create Date: 2020-05-15 23:26:14.774161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e75b522a118'
down_revision = 'ae346256b650'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('picklables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('global_name', sa.Text(), nullable=True),
    sa.Column('global_', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('un_picklable_names',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unpicklable_name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('un_picklables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unpicklable', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('un_picklables')
    op.drop_table('un_picklable_names')
    op.drop_table('picklables')
    # ### end Alembic commands ###
