"""empty message

Revision ID: 539150c4eef
Revises: 
Create Date: 2020-05-16 23:34:26.802864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '539150c4eef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('history_statement', sa.Text(), nullable=True),
    sa.Column('history_result', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('picklables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('global_name', sa.Text(), nullable=True),
    sa.Column('global_', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('un_picklable_names',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unpicklable_name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('un_picklables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unpicklable', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('un_picklables')
    op.drop_table('un_picklable_names')
    op.drop_table('picklables')
    op.drop_table('history')
    ### end Alembic commands ###
