"""empty message

Revision ID: 4ed59b604c74
Revises: 208f3a449599
Create Date: 2020-06-04 13:20:15.359550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ed59b604c74'
down_revision = '208f3a449599'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('picklables', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('un_picklable_names', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('un_picklables', sa.Column('user_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('un_picklables', 'user_id')
    op.drop_column('un_picklable_names', 'user_id')
    op.drop_column('picklables', 'user_id')
    op.drop_column('history', 'user_id')
    # ### end Alembic commands ###
